---
version: 0.2
env:
  variables:
    S3_BUCKET_NAME: order-service-build-files-bucket
    LAMBDA_FUNCTION_NAME: order-service

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Pre-build phase started on"
      - ls -la
  build:
    commands:
      - echo "Building and packaging the Lambda function with Maven..."
      - mvn clean install -P assembly-zip
  post_build:
    commands:
      - echo "Finding generated ZIP file..."
      - export ZIP_FILE_NAME=$(ls target/*.zip | grep 'aws-lambda-example-1.0-SNAPSHOT-lambda-package.zip' | xargs -n 1 basename)
      - echo "ZIP_FILE_NAME=${ZIP_FILE_NAME}"
      - echo "Uploading the deployment package to S3..."
      - aws s3 cp target/${ZIP_FILE_NAME} s3://${S3_BUCKET_NAME}/${ZIP_FILE_NAME}
      - echo "Listing S3 bucket contents..."
      - aws s3 ls s3://${S3_BUCKET_NAME}/
      - echo "Checking Lambda function exists..."
      - aws lambda get-function --function-name ${LAMBDA_FUNCTION_NAME}
      - echo "Updating the Lambda function code..."
      - aws lambda update-function-code \
          --function-name ${LAMBDA_FUNCTION_NAME} \
          --s3-bucket ${S3_BUCKET_NAME} \
          --s3-key ${ZIP_FILE_NAME}

artifacts:
  files:
    - target/aws-lambda-example-1.0-SNAPSHOT-lambda-package.zip
